apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: sast-ai-postgresql
  labels:
    app: sast-ai-orchestrator
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: SAST-AI-PostgreSQL
    type: postgres
    access: proxy
    # PostgreSQL service in sast-ai-mlops namespace
    url: sast-ai-orchestrator-postgresql:5432
    database: sast-ai
    user: quarkus
    isDefault: true
    editable: false
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: false
  valuesFrom:
    - targetPath: secureJsonData.password
      valueFrom:
        secretKeyRef:
          name: sast-ai-orchestrator-postgresql
          key: password